export const user = {
  1: {
    email: 'Gerry_Hackett77@gmail.com',
    profile: {
      avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/kevinoh/128.jpg',
      firstName: 'Liana',
      lastName: 'Crooks',
      dateOfBirth: '2018-06-14',
      gender: 'male',
      address: 'Dnipro',
      phoneNumber: '(895) 984-0132',
      skills: 'some skills here',
      experience: 'none',
    },
  },
  2: {
    email: 'Kellie.Marvin38@yahoo.com',
    profile: {
      avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/andysolomon/128.jpg',
      firstName: 'Deontae',
      lastName: 'Dare',
      dateOfBirth: '1974-12-14',
      gender: 'female',
      address: 'Kiev',
      phoneNumber: '1-615-843-3426 x600',
      skills: 'Deontare skills',
      experience: 'master everywhere',
    },
  },
};

export const task = {
  1: {
    id: 1,
    title: 'First task',
    description: 'Lorem iae!',
    status: 'To do',
    createdAt: Date.now(),
    createdForID: 1,
  },
  2: {
    id: 2,
    title: 'Second task',
    description: 'Lorem ipsumlor sit a!',
    status: 'Rewiew',
    createdAt: Date.now(),
    createdForID: 1,
  },
  3: {
    id: 3,
    title: 'Third task',
    description: 'Lorem ipsum dolor sit amet c!',
    status: 'Done',
    createdAt: Date.now(),
    createdForID: 1,
  },
  4: {
    id: 4,
    title: '4 task',
    description: 'Lorem ipsum dolor sit amet cregre ryre !',
    status: 'To do',
    createdAt: Date.now(),
    createdForID: 1,
  },
  5: {
    id: 5,
    title: '5 task',
    description: 'Lorem ipsum dolor sit amet cregre ryre !',
    status: 'To do',
    createdAt: Date.now(),
    createdForID: 2,
  },
  6: {
    id: 6,
    title: '6 task',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis voluptates voluptatum minima animi porro necessitatibus totam nisi maiores cupiditate dignissimos nulla iusto, quam asperiores veniam qui, ipsam aliquam numquam ex!',
    status: 'In progress',
    createdAt: Date.now(),
    createdForID: 2,
  },
};

export const comment = {
  1: {
    id: 1,
    content: 'ete 4t 43543 sfs ',
    createdAt: Date.now(),
    updatetAt: Date.now(),
    createdByID: 1,
    taskID: 1,
  },
  2: {
    id: 2,
    content: 'comment sfs ee tet',
    createdAt: Date.now(),
    updatetAt: Date.now(),
    createdByID: 1,
    taskID: 1,
  },
  3: {
    id: 3,
    content: 'erterte et et sfs ',
    createdAt: Date.now(),
    updatetAt: Date.now(),
    createdByID: 1,
    taskID: 2,
  },
  4: {
    id: 4,
    content: 'erterte et et sfs ',
    createdAt: Date.now(),
    updatetAt: Date.now(),
    createdByID: 1,
    taskID: 4,
  },
  5: {
    id: 5,
    content: 'erte ytr y trty rte et et sfs ',
    createdAt: Date.now(),
    updatetAt: Date.now(),
    createdByID: 1,
    taskID: 4,
  },
  6: {
    id: 6,
    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis voluptates voluptatum minima animi porro necessitatibus totam nisi maiores cupiditate dignissimos nulla iusto, quam asperiores veniam qui, ipsam aliquam numquam ex!',
    createdAt: Date.now(),
    updatetAt: Date.now(),
    createdByID: 1,
    taskID: 4,
  },
  7: {
    id: 7,
    content: 'erte ytr y ewr trty rte et et sfs ',
    createdAt: Date.now(),
    updatetAt: Date.now(),
    createdByID: 2,
    taskID: 5,
  },
  8: {
    id: 8,
    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis voluptates voluptatum minima animi porro necessitatibus totam nisi maiores cupiditate dignissimos nulla iusto, quam asperiores veniam qui, ipsam aliquam numquam ex!',
    createdAt: Date.now(),
    updatetAt: Date.now(),
    createdByID: 2,
    taskID: 6,
  },
  9: {
    id: 9,
    content: 'erte ytr y ewr trty rte et et sfs ',
    createdAt: Date.now(),
    updatetAt: Date.now(),
    createdByID: 2,
    taskID: 6,
  },
};
