const LOAD_COMMENTS = 'LOAD_COMMENTS';
const ADD_COMMENT = 'ADD_COMMENT';
const UPDATE_COMMENT = 'UPDATE_COMMENT';
const DELETE_COMMENT = 'DELETE_COMMENT';
const OPEN_EDIT_COMMENT = 'OPEN_EDIT_COMMENT';
const CLOSE_EDIT_COMMENT = 'CLOSE_EDIT_COMMENT';

export default {
  LOAD_COMMENTS,
  ADD_COMMENT,
  UPDATE_COMMENT,
  DELETE_COMMENT,
  OPEN_EDIT_COMMENT,
  CLOSE_EDIT_COMMENT,
};
