export default {
  GET_COMMENT_LIST_REQUEST: 'GET_COMMENT_LIST_REQUEST',
  GET_COMMENT_LIST_SUCCESS: 'GET_COMMENT_LIST_SUCCESS',
  GET_COMMENT_LIST_FAILURE: 'GET_COMMENT_LIST_FAILURE',

  ADD_COMMENT_REQUEST: 'ADD_COMMENT_REQUEST',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',

  UPDATE_COMMENT_REQUEST: 'UPDATE_COMMENT_REQUEST',
  UPDATE_COMMENT_SUCCESS: 'UPDATE_COMMENT_SUCCESS',
  UPDATE_COMMENT_FAILURE: 'UPDATE_COMMENT_FAILURE',

  DELETE_COMMENT_REQUEST: 'DELETE_COMMENT_REQUEST',
  DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
  DELETE_COMMENT_FAILURE: 'DELETE_COMMENT_FAILURE',

  TOGGLE_EDIT_COMMENT: 'TOGGLE_EDIT_COMMENT',
};
