export default {
  DASHBOARD_REQUEST: 'DASHBOARD_REQUEST',
  DASHBOARD_SUCCESS: 'DASHBOARD_SUCCESS',
  DASHBOARD_FAILURE: 'DASHBOARD_FAILURE',

  TASK_DETAILS_REQUEST: 'TASK_DETAILS_REQUEST',
  TASK_DETAILS_SUCCESS: 'TASK_DETAILS_SUCCESS',
  TASK_DETAILS_FAILURE: 'TASK_DETAILS_FAILURE',

  ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
  ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
  ADD_TASK_FAILURE: 'ADD_TASK_FAILURE',

  UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
  UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
  UPDATE_TASK_FAILURE: 'UPDATE_TASK_FAILURE',

  DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
  DELETE_TASK_FAILURE: 'DELETE_TASK_FAILURE',

  CLEAR_TASK_DETAILS: 'CLEAR_TASK_DETAILS',

  TOGGLE_EDIT_TASK: 'TOGGLE_EDIT_TASK',
};
